services:
  - type: web
    name: clawpress
    env: node
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: postgresql://clawpressdb_user:zSUBcqxaaAiRNbdmPkgc7y07WwLjBf01@dpg-d69vmqv5r7bs73ff983g-a.singapore-postgres.render.com/clawpressdb
      - key: AGENTMAIL_API_KEY
        value: am_0c4fe254a60572f60c1535b9b6ffd1861616a29401f103cb9b5089d41740dcab
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
    autoDeploy: true
    repo: https://github.com/Mathew-Harvey/clawpress
